{{- $name := include "redis-nodejs-demo.fullname" . -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $name }}-ing"
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  labels:
    {{- include "redis-nodejs-demo.labels" . | nindent 4 }}  
spec:
  rules:
  - host: redis-nodejs-demo.5f41657bc93448dabdbc.australiaeast.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: {{ $name }}-svc
            port: 
              number: 80