{{- $name := include "redis-nodejs-demo.fullname" . -}}

apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}-svc"
  labels:
    {{- include "redis-nodejs-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "redis-nodejs-demo.selectorLabels" . | nindent 4 }}
